# Generated by Django 2.2.16 on 2020-09-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('phone', models.CharField(default=1, max_length=100)),
                ('aphone', models.CharField(default=1, max_length=100)),
                ('country', models.CharField(default=1, max_length=100)),
                ('district', models.CharField(default=1, max_length=100)),
                ('thana', models.CharField(default=1, max_length=100)),
                ('address', models.CharField(default=1, max_length=1000)),
                ('total', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
