# Generated by Django 2.2.16 on 2020-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='aphone',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='district',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='thana',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='total',
        ),
        migrations.AddField(
            model_name='pipe',
            name='air_density',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pipe',
            name='coating_density',
            field=models.FloatField(default=81.156348),
        ),
        migrations.AddField(
            model_name='pipe',
            name='coating_thicknes',
            field=models.FloatField(default=0.0118110236220472),
        ),
        migrations.AddField(
            model_name='pipe',
            name='corrosion_allowance',
            field=models.FloatField(default=0.125),
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_density',
            field=models.FloatField(default=490),
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_diameter',
            field=models.FloatField(default=10.75),
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_thicknes',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='pipe',
            name='sea_density',
            field=models.FloatField(default=64.7),
        ),
        migrations.AddField(
            model_name='pipe',
            name='water_density',
            field=models.FloatField(default=64),
        ),
    ]
